zone_domain = "junkata.com"
frontend_record_name = "www"
app_name = "junkata-portfolio"
environment = "production"
aws_region = "ap-northeast-1"
search_console_dns_record = "google-site-verification=RYOrWjgzPqAAgHsnogDGPi3nQTR5UFhsyVcZ0K2m74Q"